#!/usr/bin/env python3
"""
sync_localization.py — generate Localizable.strings from Resources/i18n/{ko,en}.json

Sources of truth:
    Resources/i18n/ko.json   (key -> Korean)
    Resources/i18n/en.json   (key -> English)

Each top-level namespace maps to a target:
    app  -> Sources/EtchostApp/Resources/{lang}.lproj/Localizable.strings
    kit  -> Sources/EtchostKit/Resources/{lang}.lproj/Localizable.strings

Usage:
    python3 Scripts/sync_localization.py [--check]
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
I18N = ROOT / "Resources" / "i18n"
LANGS = ["ko", "en"]
LANG_NAMES = {"ko": "Korean", "en": "English"}
NAMESPACE_TARGETS = {
    "app": ROOT / "Sources" / "EtchostApp" / "Resources",
    "kit": ROOT / "Sources" / "EtchostKit" / "Resources",
}


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def read_bundle(lang: str, namespace: str) -> dict:
    data = json.loads((I18N / f"{lang}.json").read_text(encoding="utf-8"))
    return data[namespace]


def load_all() -> dict:
    bundles = {}
    for lang in LANGS:
        for namespace in NAMESPACE_TARGETS:
            bundles[(lang, namespace)] = read_bundle(lang, namespace)
    return bundles


def write_strings(path: Path, namespace: str, lang: str, entries: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"/* Generated by Scripts/sync_localization.py — do not edit. */\n"
        f"/* Source: Resources/i18n/{lang}.json ({namespace}) */\n"
    )
    lines = [header]
    for key in sorted(entries):
        lines.append(f'"{key}" = "{escape(entries[key])}";')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)} ({len(entries)} keys)")


def check(bundles: dict) -> int:
    errors = 0
    for namespace in NAMESPACE_TARGETS:
        ko, en = bundles[("ko", namespace)], bundles[("en", namespace)]
        ko_keys, en_keys = set(ko), set(en)
        if ko_keys != en_keys:
            errors += 1
            missing_ko = sorted(en_keys - ko_keys)
            missing_en = sorted(ko_keys - en_keys)
            print(f"  [ERROR] {namespace}: key mismatch")
            for k in missing_ko:
                print(f"    missing in ko.json: {k}")
            for k in missing_en:
                print(f"    missing in en.json: {k}")
        placeholders = set()
        for k, v in ko.items():
            for token in ("%@", "%d"):
                placeholders.add(f"{k}:{token}")
        for k, v in en.items():
            if "{k}" and k not in ko:
                continue
    print(f"  key parity check across all namespaces: {'OK' if errors == 0 else f'{errors} error(s)'}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Localizable.strings from i18n JSONs.")
    parser.add_argument("--check", action="store_true", help="validate key parity only")
    args = parser.parse_args()

    bundles = load_all()
    code = 0

    if args.check:
        code = check(bundles)
        return code

    for (lang, namespace), entries in bundles.items():
        target_dir = NAMESPACE_TARGETS[namespace] / f"{lang}.lproj"
        write_strings(target_dir / "Localizable.strings", namespace, lang, entries)

    print(f"synchronized {len(LANGS)} languages × {len(NAMESPACE_TARGETS)} targets")
    return code


if __name__ == "__main__":
    sys.exit(main())